### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by Aphroditefang** [klyan/JDD_Loan_Forecasting#1]
请问，在贷款金额等数据还原时，没有产生NAN吗？
为什么我在还原时报了这个错：cannot convert float NaN to integer

**Comment by klyan** [comment]
@Aphroditefang 没有，你先确认数据及其类型是否正常

**Comment by Aphroditefang** [comment]
这个是在price转换的时候出的问题，是不是price还原的时候公式也是一样的？

**Comment by klyan** [comment]
@Aphroditefang 价格解敏，用的round函数，你确认下原始数据是否有问题

**Comment by Aphroditefang** [comment]
原始数据就是下载的官方的，然后前面处理都是跟着您的处理做的啊

**Comment by klyan** [comment]
你看下解敏后为NaN的那条记录，原始数据是什么样的，把图贴一下

**Comment by Aphroditefang** [comment]
![image](https://user-images.githubusercontent.com/34327524/35087700-186cc07c-fc6c-11e7-8c5b-8d479e24c77c.png)

**Comment by Aphroditefang** [comment]
![image](https://user-images.githubusercontent.com/34327524/35087800-6d829244-fc6c-11e7-9d5c-49f7a5e9e15b.png)
但是这样看又是没有na，就不知道为什么会报那个错了。哦，对了，问一下大神，你用的是py2是么

**Comment by Aphroditefang** [comment]
t_order["order_amt"] = t_order["order_amt"] + 1
这一步为什么啊

**Comment by Aphroditefang** [comment]
uid_nearest_loan['nearest_loan_amt_time'] = uid_nearest_loan['loan_amount'] / (1 + uid_nearest_loan['nearest_loantime']) 
还有这里，为什么用最近一次贷款的金额除以（1+最近一次贷款时间），这个意义是什么啊？

**Comment by Aphroditefang** [comment]
你好，请问还在吗？我有几个问题想不明白。
1.为什么这里要+1呢？t_order["order_amt"] = t_order["order_amt"] + 1；
2.uid_nearest_loan['nearest_loan_amt_time'] = uid_nearest_loan['loan_amount'] / (1 + uid_nearest_loan['nearest_loantime'])
这里为什么用最近一次贷款的金额除以（1+最近一次贷款时间），这个意义是什么啊？
3.tr_user, ts_user区别是什么呢？

**Comment by Aphroditefang** [comment]
建模时是将11月份的贷款总额作为最目标变量是么？,还有最后是如何预测12月份的呢

**Comment by klyan** [comment]
@Aphroditefang 
1. +1 是为了做平滑（除法），
2. 最近一次贷款金额除以最近一次贷款距离现在的时间意义是：一月前借了10万，和昨天借了10万，对预测下个月借款金额是不一样的。
3. tr_user, ts_user区别是，训练集、测试集的时间周期不同
