### ISSUE TITLE
请问哪个模型可以重现榜单的成绩

### ISSUE THREAD

**Issue by zzstrwolf** [klyan/JDD_Loan_Forecasting#2]
我用了genfeature.py产生的特征，lightGBM_JDD.py中的lightgbm部分进行训练，看了下valid score，再用你的特征做CV，对比了我自己的一些local CV得分，我觉得应该达不到A榜 13th，B榜 17th吧？
请问哪部分训练代码可以重现榜单的成绩？
另外issue交流不便捷，方便加个QQ吗？66766616 微信同号

**Comment by klyan** [comment]
@zzstrwolf 我做了一些ensamble，会有一些提升，rmse其实差别不大
